version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "Restoring dependencies..."
      - dotnet restore $TEST_PROJECT/$TEST_PROJECT.csproj
      - dotnet restore TestCore/TestCore.csproj

  build:
    commands:
      - echo "Setting build configuration..."
      - |
        if [ "$TEST_ENVIRONMENT" = "Production" ]; then
          echo "TEST_CONFIGURATION=Release" > testconfig.env
        elif [ "$TEST_ENVIRONMENT" = "QA" ]; then
          echo "TEST_CONFIGURATION=QA" > testconfig.env
        else
          echo "TEST_CONFIGURATION=Debug" > testconfig.env
        fi

      - echo "Building TestCore..."
      - source testconfig.env
      - dotnet build TestCore/TestCore.csproj --no-incremental --configuration $TEST_CONFIGURATION
      - echo "Building $TEST_PROJECT..."
      - dotnet build $TEST_PROJECT/$TEST_PROJECT.csproj --no-incremental --configuration $TEST_CONFIGURATION

  post_build:
    commands:
      - echo "Running tests..."
      - source testconfig.env
      - |
        dotnet test \
          --settings $TEST_PROJECT/.runsettings \
          --logger "trx;LogFileName=TestResults.trx" \
          --filter $TEST_FILTER \
          --configuration $TEST_CONFIGURATION

artifacts:
  files:
    - '$TEST_PROJECT/bin/**/TestResults/**/*'
  discard-paths: no
  base-directory: .
  name: artifact-$(date +%Y-%m-%d)

cache:
  paths:
    - '!**/bin/Debug/**'
    - '!**/obj/Debug/**'
    - $TEST_PROJECT/bin
    - $TEST_PROJECT/obj
    - TestCore/bin
    - TestCore/obj
  type: LOCAL
  modes:
    - LOCAL_CUSTOM_CACHE
