global using System.Net;
global using Microsoft.Extensions.Configuration;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using MockProject.Exceptions;
global using MockProject.Pages;
global using OpenQA.Selenium;
global using OpenQA.Selenium.Firefox;
global using OpenQA.Selenium.Support.UI;
global using WebDriverManager.DriverConfigs.Impl;
