name: Main workflow

on:
  push:
    branches:
      - main
    paths:
      - "SeleniumTestFramework/**"
      - "TestCore/**"

jobs:
  test:
    env:
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set configuration based on environment
        run: |
          if [ "${{ vars.TEST_ENVIRONMENT }}" = "Production" ]; then
            echo "TEST_CONFIGURATION=Release" >> $GITHUB_ENV
          elif [ "${{ vars.TEST_ENVIRONMENT }}" = "QA" ]; then
            echo "TEST_CONFIGURATION=QA" >> $GITHUB_ENV
          else
            echo "TEST_CONFIGURATION=Debug" >> $GITHUB_ENV
          fi
          echo "Configuration set to $TEST_CONFIGURATION"

      - name: Restore dependencies and build
        run: |
          dotnet restore TestCore/TestCore.csproj
          dotnet restore ${{ vars.TEST_PROJECT }}/${{ vars.TEST_PROJECT }}.csproj
          dotnet build TestCore/TestCore.csproj --no-incremental --configuration $TEST_CONFIGURATION
          dotnet build ${{ vars.TEST_PROJECT }}/${{ vars.TEST_PROJECT }}.csproj --no-incremental --configuration $TEST_CONFIGURATION

      - name: Run tests and generate reports
        run: |
          dotnet test \
            --settings ${{ vars.TEST_PROJECT }}/.runsettings \
            --logger "trx;LogFileName=TestResults.trx" \
            --filter ${{ vars.TEST_FILTER }} \
            --configuration $TEST_CONFIGURATION

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: ${{ vars.TEST_PROJECT }}/TestResults

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
