name: Test workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    environment: Production
    env:
      TEST_ENVIRONMENT: Production
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
    runs-on: ubuntu-24.04
    steps:
      - name: Pull code
        uses: actions/checkout@v4
      - name: Restore dependencies and build
        run: dotnet restore && dotnet build --no-incremental --configuration Release
      - name: Test
        run: dotnet test --settings MockProject/.runsettings
