name: Production
on:
  push:
    branches:
      - main
jobs:
  test:
    env:
      TEST_ENVIRONMENT: prod
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v4
      - name: Restore dependencies and build
        run: dotnet restore && dotnet build
      - name: Test
        run: dotnet test --settings=MockProject/.runsettings
